#docker_compose.yaml
version: '3'

services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./app:/app
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calculator
    ports:
      - "3306:3306"
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql